### ISSUE TITLE
Blank window (Mac)

### ISSUE THREAD

**Issue by 7890** [drobilla/pugl#14]
An observation on Mac OSX:
Running `pugl_test` shows a blank (white) window. The first time it's resized (if allowed), it becomes black. All keyboard and mouse entry is processed correctly BUT the scene is never drawn. Adding a printf to `onDisplay()` shows that this function is never called. The FPS stats reflect this: "0 frames in 5 seconds = 0.000 FPS". Can anybody confirm this behavior? I encounter it on macOS High Sierra Version 10.13.6. Thanks for any hints.

**Comment by 7890** [comment]
in `pugl_test.c` `onEvent()`, the `case PUGL_EXPOSE` never happens.

**Comment by 7890** [comment]
Again, it's unclear if this is the right place and correct approach to receive PUGL_EXPOSE events:
https://github.com/drobilla/pugl/blob/908e249c8030698e4313df9aeb81cfb7763e5150/pugl/detail/mac.m#L851
However adding these lines:
```
        //prevent expose when hidden
        if( ![view->impl->window isVisible] ) {return;}

        [view->impl->wrapperView setNeedsDisplay: YES];

        //create and dispatch expose event
        const NSRect rect = [view->impl->wrapperView bounds];
        const PuglEventExpose ev =  {
                PUGL_EXPOSE,
                0,
                rect.origin.x,
                rect.origin.y,
                rect.size.width,
                rect.size.height,
                0
        };

        puglDispatchEvent(view, (const PuglEvent*)&ev);
```
fixed the initial problem.

**Comment by drobilla** [comment]
You can't dispatch expose events directly there.

**Comment by 7890** [comment]
OK, but `- (void) drawRect:(NSRect)rect` in window delegate where `PUGL_EXPOSE` is dispatched seems never called (or i missed it). I've tried with `NSLog(@"...")` to check this. Does it work at your end as currently is?

**Comment by drobilla** [comment]
Your description of the issue isn't very clear.  The initial display, if continuous drawing is off, does not happen until any event occurs, yes, and then everything (not just black) draws correctly.

I am not yet sure why.  You can't fix initial display by aggressively spamming hard redraws in `puglPostRedisplay` because, aside from many other issues, it bogs down every other case.

**Comment by 7890** [comment]
Interesting .. 
I've just tried again, making sure I use recent git. I compile the lib and the test program, put both into an .app directory structure. Running it with or without `-c` shows the same result. White window (funnily enough the round edges are black). No events can make the cube show up. Only if `-r`is set, resizing the window makes it all black. It looks like the `PUGL_EXPOSE` event is not generated for some reason which is strange if it works for you, meh.

**Comment by 7890** [comment]
On a related note, the x11 test program run with `-c` is generating a continuous storm of `PUGL_EXPOSE` events. So it's about where the event is generated I suppose, not the fact that there _is_ a storm (?).

**Comment by drobilla** [comment]
... of course it is.  That's what continuous means.

I find this rather unlikely with continuous drawing on.  Since you are apparently stitching together a janky bundle manually, I would guess it's broken.  Countless things don't work on MacOS if a graphical app is not in a bundle.  Please reproduce this with _exactly_ the upstream code using the included build system.

**Comment by 7890** [comment]
That's the idea, use the official build system and put pugl_test into the most minimal bundle. I'll look out for something odd in the bundle, thanks.

**Comment by 7890** [comment]
I'm pretty sure it's using exactly upstream code, basically this is how bundle is created:
```
./waf build && sudo ./waf install

gcc -v -o pugl_test test/pugl_test.c build/libpugl_mac.a build/libpugl_mac_gl.a -I. -framework OpenGL -framework CoreFoundation -framework AppKit

cp pugl_test MyApp.app/Contents/MacOS/MyApp
```
I wonder where I could put the next NSLog() to track this down.

**Comment by 7890** [comment]
I will try with the "App" branch next to see if it makes a difference.

**Comment by mfisher31** [comment]
I'm experiencing this as well in the upstream source.  Same blank window whether continuous or not.  The problem is that the GL view is a child of the wrapper view and the OS doesn't ever call drawRect on it.

nutshell `[view->impl->wrapperView setNeedsDisplay: YES];` does nothing.

Either the parent view needs an animation layer, or something else like the code above which was rejected.  Why can't events be dispatched from there? Couldn't you say the same thing for drawRect itself? <-- this method is supposed to paint to a graphics context, not send events.

**Comment by mfisher31** [comment]
Using NSTimer also works, but honestly the suggest change works great.  The expose causes client code to draw in the GL context and it just updates all on its own.

**Comment by mfisher31** [comment]
> I'm pretty sure it's using exactly upstream code, basically this is how bundle is created:
> 
> ```
> ./waf build && sudo ./waf install
> 
> gcc -v -o pugl_test test/pugl_test.c build/libpugl_mac.a build/libpugl_mac_gl.a -I. -framework OpenGL -framework CoreFoundation -framework AppKit
> 
> cp pugl_test MyApp.app/Contents/MacOS/MyApp
> ```
> 
> I wonder where I could put the next NSLog() to track this down.



> I'm pretty sure it's using exactly upstream code, basically this is how bundle is created:

I think @drobilla means do `./waf configure --tests` so that the test app builds along with the librarys and check it that way.  I've done this, and get the same results you describe.  Bug is legit

**Comment by 7890** [comment]
@mfisher31 strangely `--tests` is not understood by waf here.
Just now I understand that there's infrastructure in place in wscript to create the minimal app bundle for macOS. I guess `--tests` needs a closer look. Also i can't see any configure output indicating whether or not test is going to be built or not (?). I've not seen a binary produced by waf, these are the reasons I've had to compile it separately, looking at `--tests` now.

**Comment by 7890** [comment]
This patch brought back `--tests`. For some reason, BUILD_TESTS wasn't good.
```
diff --git a/wscript b/wscript
index 796a9ce..6003a90 100644
--- a/wscript
+++ b/wscript
@@ -35,12 +35,14 @@ def options(ctx):
          'no-static':   'do not build static library',
          'no-shared':   'do not build shared library',
          'log':         'print GL information to console',
-         'grab-focus':  'work around keyboard issues by grabbing focus'})
+         'grab-focus':  'work around keyboard issues by grabbing focus',
+         'tests':       'build tests'})
 
 
 def configure(conf):
     conf.env.ALL_HEADERS     = Options.options.all_headers
     conf.env.TARGET_PLATFORM = Options.options.target or sys.platform
+    conf.env.WITH_TESTS      = Options.options.tests
     conf.load('compiler_c', cache=True)
     conf.load('autowaf', cache=True)
 
@@ -80,7 +82,7 @@ def configure(conf):
     # Shared library building is broken on win32 for some reason
     conf.env.update({
         'BUILD_SHARED': not Options.options.no_shared,
-        'BUILD_STATIC': conf.env.BUILD_TESTS or not Options.options.no_static})
+        'BUILD_STATIC': conf.env.WITH_TESTS or not Options.options.no_static})
 
     autowaf.set_lib_env(conf, 'pugl', PUGL_VERSION)
     conf.write_config_header('pugl_config.h', remove=False)
@@ -91,7 +93,8 @@ def configure(conf):
          "Build shared library":   bool(conf.env.BUILD_SHARED),
          "OpenGL support":         conf.is_defined('HAVE_GL'),
          "Cairo support":          conf.is_defined('HAVE_CAIRO'),
-         "Verbose console output": conf.is_defined('PUGL_VERBOSE')})
+         "Verbose console output": conf.is_defined('PUGL_VERBOSE'),
+         "Build test program":     conf.is_defined('WITH_TESTS')})
 
 
 def _build_pc_file(bld, name, desc, target, libname, deps={}, requires=[]):
@@ -259,7 +262,7 @@ def build(bld):
             install_path = '',
             **kwargs)
 
-    if bld.env.BUILD_TESTS:
+    if bld.env.WITH_TESTS:
         if bld.is_defined('HAVE_GL'):
             build_test('pugl_test', platform, 'gl', uselib=['M'])
 ```
Next up: try it out on macOS with bundling

**Comment by mfisher31** [comment]
It might just be `--test` ?  also, I made a `ui:Cocoa` test GUI... same results.  so it's not just the running as an application.

**Comment by drobilla** [comment]
The general problem with forcing draws in weird places is that the window system is no longer in control of that, so you get redundant drawing, reduced framerate, less smoothness, and so on.  It also screws up the order of expose with respect to other things like configure.  It's just generally problematic to do things outside the normal event loop event pipeline.

The above looks like a more correct fix, thanks.  I'll try it out.

**Comment by mfisher31** [comment]
Yeah, sorry I got a little jumpy there.  At the moment I don't have  good Linux machine, therefore do most of my stuff on a Mac, which is why I'm highly motivated to fix OSX specific items.

Also, do you prefer issues and and contributions to be submitted on gitlab?  Seems like it's the more official place to do things.

**Comment by drobilla** [comment]
> Yeah, sorry I got a little jumpy there. At the moment I don't have good Linux machine, therefore do most of my stuff on a Mac, which is why I'm highly motivated to fix OSX specific items.

Hey, works for me!  While I of course have a Mac, I only use it when I have to :)

> Also, do you prefer issues and and contributions to be submitted on gitlab? Seems like it's the more official place to do things.

Yeah, I'm slowly moving everything officially to Gitlab, and all the nice infrastructure is set up there.  Ultimately I'd like to do a better job with organization and planning and so on which will require consolidating things more there.

Currently I bounce everything off Gitlab anyway since that's where CI checks that everything actually builds everywhere, but since I do the flat history thing and merge manually it doesn't really make any difference to me where things come from if you prefer Github (or some other repo, or email, or whatever).

**Comment by drobilla** [comment]
0706f4a121f6f9c5b96a19c4272a8636fc230cbc

**Comment by mfisher31** [comment]
@drobilla - heads up, I pulled the latest master and blank window fixes disappeared.  0706f4a was lost in `master` somehow.  Accident? or did some other problem arise?

**Comment by drobilla** [comment]
@mfisher31 Do you mean literally?  That commit is still on master as far as I can tell.

It was a tricky rebase when merging the big API branch though, so I could have screwed up the behavior.  I thought I was careful to preserve it, but could have screwed it up (particularly since I never saw the same issue to begin with).

**Comment by mfisher31** [comment]
Originally I thought literally. Was confused seeing all the other commits that came in on top of mine.  And on top of that, was working with a submodule in lvtk which points to my fork.

Sorry for the confusion on that.

I did notice doing a recompile that the definition for `- (void) dispatchConfigure:(NSRect)bounds;` went missing.

```
[14/21] Linking build/libpugl_mac_gl.a
[15/21] Linking build/libpugl_mac_gl.dylib
../pugl/detail/mac.m:95:17: warning: method definition for 'dispatchConfigure:' not found [-Wincomplete-implementation]
@implementation PuglWrapperView
                ^
/Users/mfisher/workspace/kv/pugl/pugl/detail/mac.h:39:1: note: method 'dispatchConfigure:' declared here
- (void) dispatchConfigure:(NSRect)bounds;
^
1 warning generated.

../pugl/detail/mac.m:95:17: warning: method definition for 'dispatchConfigure:' not found [-Wincomplete-implementation]
@implementation PuglWrapperView
                ^
/Users/mfisher/workspace/kv/pugl/pugl/detail/mac.h:39:1: note: method 'dispatchConfigure:' declared here
- (void) dispatchConfigure:(NSRect)bounds;
^
1 warning generated.
```
