### ISSUE TITLE
PuglWorld: access for Display* 

### ISSUE THREAD

**Issue by osch** [drobilla/pugl#18]
Hi, I'm very interested in the latest development for multi view pugl.

For the `PuglView` the native window handle can be accessed with  `puglGetNativeWindow`. 

What do you think about implementing a similar access to the underlying native handle for the `PuglWorld`? For X11 this would be the `Display*`. By looking at the code for the other plattforms it seems to me that there is nothing similiar for other platforms (NSApplication on mac is singleton). See also my implementation of `puglGetNativeDisplay` for X11: https://github.com/osch/pugl/commit/59e03dd1bf22ff0deca561422d371dcb2a31530e

Such access could be useful for a lot of things but I need it especially for creating pixmap cairo surfaces on the X11 server independently from the views. This could be solved externally if the `Display*` can be reached. But it could also be a good idea to integrate this feature into `PuglWorld`: a new function to create a cairo pixmap surface independently from the PuglViews that will match the current screen device and will be on the display server for x11. What do you think of this approach?

**Comment by drobilla** [comment]
> By looking at the code for the other plattforms it seems to me that there is nothing similiar for other platforms

It's worse, there is similar Cairo functionality for all the platforms, but all of the others require an actual drawing context to create a compatible surface.  This pattern itself is non-portable.

> I need it especially for creating pixmap cairo surfaces on the X11 server independently from the views

Why?

> a new function to create a cairo pixmap surface independently from the PuglViews that will match the current screen device and will be on the display server for x11. What do you think of this approach?

I don't think it's appropriate for the Pugl API to have X11 and Cairo specific things in it.  Maybe if this concept could be mapped to some reasonable portable API and implemented by backends, and it made sense for arbitrary backends, but that seems questionable, and doesn't fit the design where backends are part of views anyway.

Exposing the display isn't so bad, and it's simple, so I'm not opposed to it, but it smells a bit since the concept doesn't map to the other platforms and it seems like the thing you are doing fundamentally doesn't work on them at all, so I'd like to understand why you want to create a server-side surface but have no view to base it on.

**Comment by osch** [comment]
> I don't think it's appropriate for the Pugl API to have X11 and Cairo specific things in it.

Yes in principle the normal Pugl API should be platform agnostic but in more complicated cases the application could also have some platform specific parts and for these cases it could be useful to get acccess to some specific details in pugl. One idea could be to  provide for theses cases some public platform specific functions, e.g. just having a non static function `puglX11GetDisplay` in `x11.c`.

> I'd like to understand why you want to create a server-side surface but have no view to base it on.

There are two possible reasons for this: 

1.) The application wants to do some cairo layout stuff (e.g. obtaining text extents) independently from the window. For this a cairo context is needed that matches the screen device. This could be a minimal invisible buffer for example. 

2.) The application wants to pre-render bitmaps that are later on drawn frequently on the screen. For this the bitmap should ideally be compatible to the screen device. For X11 it gives better perfornance to have these bitmaps on the server side (at least if you are using X11 over a remote connection).

> t's worse, there is similar Cairo functionality for all the platforms, but all of the others require an actual drawing context to create a compatible surface. This pattern itself is non-portable.

Well for windows you can call `CreateCompatibleDC(NULL);` it will create a memory DC compatible with the application's current screen.

**Comment by drobilla** [comment]
Fair enough.  I am a bit hesitant to hastily add stuff about "screens" and "displays" though, since if fullscreen is to be added some kind of proper API about actual physical displays needs to be added.  I guess this is just a naming problem though.

It might as well return the application on MacOS, though as you say that's static so this isn't terribly useful.  I don't think there is anything at all on Windows that fits the "connection to system" role.

What kind of application are you writing where you don't have some "main" view to use anyway?  I am becoming increasingly unsure that multiple views was even a good idea to add at all, to be honest.  This stuff can be a total nightmare when multiple displays and such get involved, I think it's best avoided if at all possible; `cairo_surface_create_similar()` is nice, it lets you get this without having to be all hairy with screen/etc details.

**Comment by osch** [comment]
> What kind of application are you writing where you don't have some "main" view to use anyway?

I'm trying to build a Pugl binding for the [Lua](https://www.lua.org/) scripting language with a thin wrapper for handling multiple widget objects to make it as simple as possible writing a Cairo gui using Lua to implement the widget objects. For this it seems natural and easy to have a Cairo layout context independently from the views. Otherwise the script code has to be careful to use some functionality only in conjunction with a window. I would restrict the access to the window's cairo context only while processing expose events and not allow to use it outwards for layout purposes. With this there is a strict separation between drawing and layout (or pre-drawing to surfaces that are derived from the layout contest. 

IMHO it would also be useful if PuglWorld would contain a Cairo layout context. It could be accessible through a backend specific function `puglCairoGetLayoutContext(PuglWorld*)` and it could be lazy constructible so it doesn't exist if it is not used. Then the application could call `cairo_surface_create_similar()` for creating off screen pre-rendered buffers that are on the server side for X11. What do you think of this idea?

>  am becoming increasingly unsure that multiple views was even a good idea to add at all, to be honest. This stuff can be a total nightmare when multiple displays and such get involved,

Well, I like Pugl's multiple views implementation, I even implemented it myself (but only for X11) in my local copy, than I detected that you are also working on this. I very much like the simplicity of Pugl and the idea to separate the event and window handling functionality from the drawing backend. This is a very elegant and lightweight construction without global state that perfectly matches Lua which also doesn't have global state. The multiple views feature will increase the area where Pugl could be used largely to make it useful not only for plugins.

**Comment by 7890** [comment]
Apropos screen, my pugl tells me 
```
Found 1 screen(s), using [0]
	[0]: 1920 x 1200
Using visual 0x8B: R=8 G=8 B=8 A=8 D=24 DOUBLE=0 SAMPLES=0
WM: Openbox
```
:)

> I am becoming increasingly unsure that multiple views was even a good idea to add at all, to be honest.

It has something very appealing but `world` makes it more complicated indeed (compared to single view).

**Comment by 7890** [comment]
@osch the scripts could draw to an off-screen buffer unrelated to a window and then blit it to the view/window when draw is due ~
> Otherwise the script code has to be careful to use some functionality only in conjunction with a window.

+1 for Lua bindings !

**Comment by drobilla** [comment]
Sorry, life and other things got in the way and I'm a bit behind.

++ Lua bindings in general.

I would really rather not add complexity like "layout contexts" (which seems pretty hard to define in a general way) if at all possible, and it seems like this would really poke a hole in the design you mentioned, which I'm also (finally) quite happy with.  Adding view-specific things to the world just seems like a world of hurt.

So, to me it seems like the original suggestion of adding access to Display* somehow is best.  This should allow almost anything, avoiding the problem of people forever wanting this and that specific thing added to Pugl, and it's easy enough to define.  If it doesn't mean anything on Windows (or wherever) and just returns NULL, it's no big deal.  Personally I wouldn't actually use it in this way because it's fundamentally non-portable (to Windows), but I don't see a good way around that and that's your call anyway.  Pugl's job is to enable people to do what they want while being as minimal as possible itself.  Access to the `Display*` seems fully in-line with that mission, in the same way that using native window pointers does.

So I think I'll adapt your PR (thanks) to be at least conceptually general and go with that.

**Comment by drobilla** [comment]
https://github.com/drobilla/pugl/commit/d53ce364a7c7c0d9b0d1fa87077df2dff69688e9
