### ISSUE TITLE
Events not fired (Windows)

### ISSUE THREAD

**Issue by 7890** [drobilla/pugl#6]
I made this observation on Windows:

Program pugl_test works as expected, except the following:

- PUGL_ENTER_NOTIFY, PUGL_LEAVE_NOTIFY, PUGL_FOCUS_IN and PUGL_FOCUS_OUT are never emitted 

- Window is black until mouse enters the first time (first drawing of cube)

- Window doesn't repaint when resized (until mouse enters window again)

The latter two might be a side-effect of events not fired (?).

**Comment by 7890** [comment]
This could be partially solved with this line:
https://github.com/drobilla/pugl/pull/8/files#diff-185913b987b39e2648d6856a734a4694R482
However the window contents aren't redrawn _while_ resizing the window.

**Comment by drobilla** [comment]
Please file concrete issues, not grab bags of unrelated things.

You have to manually implement timer hacks to animate while resizing both on Windows 93216a6 and MacOS ae9a099.

Initial display on Windows is fixed in aa7fb0a and fe920b2.

Enter/leave is implemented on Windows in 5192224 and MacOS in 38b4790.

Focus is implemented on Windows in b5ef912.
